Summary: bundle2rpm Package
Name: |package_name|
Version: |package_version|
Release: |package_release|
License: |license|
Group: Applications/RubyGems
URL: |url|
BuildRoot: %{_tmppath}/%{name}-root
Prefix: %(echo %{_prefix})
AutoProv: no

%description
This package was generated by bundle2rpm. It contains a deployed Gem bundle which
may contain one or more individual Ruby Gems.

%install
[ -d ${RPM_BUILD_ROOT} ] && rm -rf ${RPM_BUILD_ROOT}
install -d ${RPM_BUILD_ROOT}%{_prefix}
cp -R ${RPM_SOURCE_DIR}/* ${RPM_BUILD_ROOT}%{_prefix}

find ${RPM_BUILD_ROOT}%{_prefix} \( \( -type f -o -type l \) -printf '"%%p"\n' \) \
        -o \( -type d -a -printf '%%%%dir "%%p"\n' \) \
        | sed "s@${RPM_BUILD_ROOT}@@g" \
        > bundle.lst

# Remove the first line, it's the prefix-dir which we do not
# want under rpm control:
sed -i 1d bundle.lst

%post
#!/bin/bash
bundle_dir="%{_prefix}/%{name}-%{version}-%{release}"
sed -i "s@REPLACE_WITH_BUNDLE_DIR@${bundle_dir}@g" ${bundle_dir}/.bundle/*
sed -i "s@REPLACE_WITH_BUNDLE_DIR@${bundle_dir}@g" ${bundle_dir}/bin/*

%clean
[ -d ${RPM_BUILD_ROOT} ] && rm -rf ${RPM_BUILD_ROOT}

%files -f bundle.lst
%defattr(-,|user|,|group|,-)

%changelog
|changelog|
